var lang={
	Load_More:"Загрузить ещё...",
	Attribute:"Аттрибут",
	Value:"Значение",
	Statistics:"Статистика",
	//api
	films:"Фильмы",
	starships:"Используемые звёздные корабли",
	vehicles:"Используемый транспорт",
	species:"Биологический вид(-ы)",
	planets:"Планеты",
	people:"Люди",
	//people
	birth_year:"Дата рождения",
	eye_color:"Цвет глаз",
	gender:"Пол",
	hair_color:"Цвет волос",
	height:"Высота",
	homeworld:"Родная планета",
	mass:"Масса",
	name:"Имя",
	skin_color:"Цвет кожи",
	created:"Информация опубликована",
	edited:"Информация изменена",
	url:"Ссылка на данные",
	//films
	characters:"Персонажи",
	episode_id:"Номер эпизода",
	opening_crawl:"Вступительные титры",
	producer:"Продюсер",
	release_date:"Дата выхода",
	title:"Название",
	//starships
	MGLT:"Скорость в световых годах",
	cargo_capacity:"Вместимость грузового отсека",
	consumables:"Запасов хватит на",
	cost_in_credits:"Цена в кредитах",
	crew:"Минимальное количество персонала",
	hyperdrive_rating:"Рейтинг гипер-ускорения",
	length:"Длина корабля",
	manufacturer:"Производитель",
	max_atmosphering_speed:"Максимальная скорость в атмосфере",
	model:"Модель",
	passengers:"Количество пассажиров",
	pilots:"Пилоты",
	starship_class:"Тип корабля",
	//vehicles
	vehicle_class:"Тип транспорта",
	//species
	average_height:"Максимальная высота",
	average_lifespan:"Продолжительность жизни",
	classification:"Класс",
	designation:"Обозначение",
	eye_colors:"Цвета глаз",
	hair_colors:"Цвета волос",
	language:"Язык",
	//planets
	climate:"Климат",
	diameter:"Диаметр",
	gravity:"Гравитация",
	orbital_period:"Период обращения вокруг планеты",
	population:"Население",
	residents:"Жители",
	rotation_period:"Период обращения",
	surface_water:"Есть ли вода",
	terrain:"Местность"
}